"""
Author: Ben Janis
Date: 2025

This source file is part of an example system for MITRE's 2025 Embedded System CTF
(eCTF). This code is being provided only for educational purposes for the 2025 MITRE
eCTF competition, and may not meet MITRE standards for quality. Use this code at your
own risk!

Copyright: Copyright (c) 2025 The MITRE Corporation
"""

import argparse
import json
from pathlib import Path
import struct
from ectf25_design.gen_secrets import load_secret
from ectf25_design.utils import *


from loguru import logger

from Crypto.Cipher import AES

def gen_subscription(
    secrets: bytes, device_id: int, start: int, end: int, channel: int
) -> bytes:
    """Generate the contents of a subscription.

    The output of this will be passed to the Decoder using ectf25.tv.subscribe

    :param secrets: Contents of the secrets file generated by ectf25_design.gen_secrets
    :param device_id: Device ID of the Decoder
    :param start: First timestamp the subscription is valid for
    :param end: Last timestamp the subscription is valid for
    :param channel: Channel to enable
    
    :returns: The encrypted subscription
    :rtype: bytes
    
    :format specification for subscription.bin:
    https://jhu-mitre-ectf.atlassian.net/wiki/spaces/BT/pages/3768335/Binary+Data+Format+Specifications
        4 bytes: device_id (uint32_t)
        8 bytes: start_timestamp (uint64_t)
        8 bytes: end_timestamp (uint64_t)
        4 bytes: channel (uint32_t)
        60 bytes: encrypted_channel_key (12 bytes nounce + 32 bytes encrypted_key + 16 bytes tag)
        64 bytes: ed25519_signature (sign device_id+start_timestamp+end_timestamp+channel+encrypted_channel_key)
    """
    # Load secrets into a dictionary
    secrets = load_secret(secrets)
    # check if channel is supported (not enabled when secret generation)
    try:
        secrets["channel_keys"][channel]
    except Exception:
        raise ValueError(f"Channel {channel} is not supported!")
            
    
    #https://stackoverflow.com/questions/67307689/decrypt-an-encrypted-message-with-aes-gcm-in-python#:~:text=6,posted%20for%20encryption%3A
    aes_acm_packet = aes_gcm_encrypt(secrets["channel_keys"][channel], secrets["subscription_key"])
    assert len(aes_acm_packet) == 60, f"length error: aes_acm_packet length is {len(aes_acm_packet)}"
    # sign the subscription
    signature = ed25519_sign(struct.pack("<IQQI60s", device_id, start, end, channel, aes_acm_packet),\
        secrets["signature_private_key"])
    # Pack the subscription. This will be sent to the decoder with ectf25.tv.subscribe
    ret = struct.pack("<IQQI60s64s", device_id, start, end, channel, aes_acm_packet, signature)
    assert ed25519_verify(ret[-64:], ret[:-64], secrets["signature_public_key"]) == True, "signature generation error"
    return ret


def parse_args():
    """Define and parse the command line arguments

    NOTE: Your design must not change this function
    """
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--force",
        "-f",
        action="store_true",
        help="Force creation of subscription file, overwriting existing file",
    )
    parser.add_argument(
        "secrets_file",
        type=argparse.FileType("rb"),
        help="Path to the secrets file created by ectf25_design.gen_secrets",
    )
    parser.add_argument("subscription_file", type=Path, help="Subscription output")
    parser.add_argument(
        "device_id", type=lambda x: int(x, 0), help="Device ID of the update recipient."
    )
    parser.add_argument(
        "start", type=lambda x: int(x, 0), help="Subscription start timestamp"
    )
    parser.add_argument("end", type=int, help="Subscription end timestamp")
    parser.add_argument("channel", type=int, help="Channel to subscribe to")
    return parser.parse_args()


def main():
    """Main function of gen_subscription

    You will likely not have to change this function
    """
    # Parse the command line arguments
    args = parse_args()

    subscription = gen_subscription(
        args.secrets_file.read(), args.device_id, args.start, args.end, args.channel
    )

    # Print the generated subscription for your own debugging
    # Attackers will NOT have access to the output of this (although they may have
    # subscriptions in certain scenarios), but feel free to remove
    #
    # NOTE: Printing sensitive data is generally not good security practice
    logger.debug(f"Generated subscription: {subscription}; subscription length: {len(subscription)}")

    # Open the file, erroring if the file exists unless the --force arg is provided
    with open(args.subscription_file, "wb" if args.force else "xb") as f:
        f.write(subscription)

    # For your own debugging. Feel free to remove
    logger.success(f"Wrote subscription to {str(args.subscription_file.absolute())}")


if __name__ == "__main__":
    main()
